baseURL: https://blog.lightquantum.me
languageCode: zh-cn
title: 光子の胡话
theme: mini

# Default content language, support en (English) / zh (Chinese) / nl (Dutch) / fr (French), default 'en'
defaultContentLanguage: zh

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: your-google-analytics-id
disqusShortname: lightquantum-blog

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  github: "https://github.com/PhotonQuantum"
  twitter: "https://twitter.com/LightQuantumhah"

# Site parameters
params:
  # Site Author
  author: LightQuantum
  # Author biography
  bio: 一颗正在寻求解脱的迷茫心灵
  # Site Description, used in HTML meat
  description: 一颗正在寻求解脱的迷茫心灵


  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  enableComments: false
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: false
  # To enable table of content, you could set `showToc: true`, default is `false`
  showToc: true
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: true
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: false
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: false
  # Website copy write, default: '© Copyright 2021 ❤️ {params.author}'
  copyright: '' 

  # Extra links in navigation
  links:
    - name: 关于
      path: https://lightquantum.me
    ## e.g.
    # - name: Project
    #   path: /project

  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    ## e.g.
    # - css/custom.css # local css in `static/css/custom.css`
    # - https://example.com/custom.css # remote css
  customJS:
    ## e.g.
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js

  valine:
    enable: true
    appId: J8avBck0dHMSTeY5ao32NgK6-MdYXbMMI
    appKey: rNs4DmGeI6INKdXRsB7RQGUV
    serverURLs: https://eusqn6yi.api.lncldglobal.com
